# Generated by Django 5.0.6 on 2024-06-10 12:34

import shows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="showsession",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[shows.models.validate_price],
            ),
        ),
    ]
