# Generated by Django 5.0.6 on 2024-06-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0003_remove_astronomyshow_unique_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showsession",
            name="show_time",
            field=models.DateTimeField(),
        ),
    ]
